name: CI/CD to Production via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    name: Deploy and Test on Staging
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Staging and run deploy.sh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSHE_SSH_KEY }}
          script: |
            bash /app/deploy.sh kazuki_matsushiba

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-to-staging  # ← staging成功後に実行

    steps:
      - name: SSH to Production and run deploy.sh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          port: ${{ secrets.PRODUCTION_PORT }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            git config --global --add safe.directory /app
            bash /app/deploy.sh kazuki_matsushiba
